import { Command } from "@commander-js/extra-typings";
import chalk from "chalk";
import { getMachineHash } from "../base.js";

export const createHashCommand = () => {
    return new Command("hash")
        .description(
            "Converts the binary generated by the build command to hexadecimal and prints out the result to console.",
        )
        .option("--json", "Format output as json.")
        .action(async ({ json }, command) => {
            const hash = await getMachineHash();
            if (hash) {
                if (!json) {
                    console.log(
                        `${chalk.green("?")} Cartesi machine templateHash ${chalk.cyan(hash)}\n`,
                    );
                } else {
                    process.stdout.write(JSON.stringify({ hash }));
                }
            } else {
                command.error(
                    `Cartesi machine snapshot not found, run 'build'`,
                );
            }
        });
};
