services:
    solver:
        image: ghcr.io/zippiehq/cartesi-coprocessor-solver:v1.1.0
        container_name: cartesi-coprocessor-solver
        ports:
            - 127.0.0.1:3034:3034
        depends_on:
            anvil:
                condition: service_healthy
            setup-operator:
                condition: service_completed_successfully
        volumes:
            - ./files/config.toml:/cartesi-coprocessor-solver/config.toml
