[install]
linkWorkspacePackages = false

[test]
coverage = true
coverageReporter = ["text", "lcov"]
coverageDir = "./coverage"
coverageSkipTestFiles = true
coveragePathIgnorePatterns = "**/tests/**/*.ts"
