services:
    validator:
        image: cartesi/rollups-node:devel
        depends_on:
            migration:
                condition: service_completed_successfully
            anvil:
                condition: service_healthy
        expose:
            - "10000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:10000/livez"]
            interval: 10s
            timeout: 1s
            retries: 5
        user: root
        command:
            - /bin/bash
            - -c
            - |
                mkdir -p "$CARTESI_SNAPSHOT_DIR"
                cp --recursive /tmp/snapshot/* "$CARTESI_SNAPSHOT_DIR"
                exec cartesi-rollups-node

        env_file:
            - ${CARTESI_BIN_PATH}/node/default.env

    proxy:
        depends_on:
            validator:
                condition: service_healthy

    prompt:
        image: debian:bookworm-slim
        environment:
            PROMPT_TXT_03_INSPECT: "Inspect running at http://localhost:${CARTESI_LISTEN_PORT}/inspect/"

    traefik-config-generator:
        environment:
            TRAEFIK_CONFIG_INSPECT_SERVER: |
                http:
                    routers:
                        inspect_server:
                            rule: "PathPrefix(`/inspect`)"
                            service: inspect_server
                    services:
                        inspect_server:
                            loadBalancer:
                                servers:
                                    - url: "http://validator:10000/inspect"
