services:
    database:
        image: postgres:16-alpine
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            - POSTGRES_PASSWORD=password

    migration:
        extends:
            file: ${CARTESI_BIN_PATH}/node/docker-compose-base.yaml
            service: rollups_node_image
        command:
            - /bin/bash
            - -c
            - -x
            - |
                cartesi-rollups-cli db upgrade -p "$$CARTESI_POSTGRES_ENDPOINT"

        depends_on:
            database:
                condition: service_healthy
        restart: "no"
        env_file:
            - ${CARTESI_BIN_PATH}/node/default.env
