services:
    validator:
        image: cartesi/rollups-node:1.5.1
        depends_on:
            dapp_deployer:
                condition: service_completed_successfully
        expose:
            - "10000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:10000/healthz"]
            interval: 10s
            timeout: 1s
            retries: 5
        command:
            - /bin/bash
            - -c
            - |
                mkdir -p "$CARTESI_SNAPSHOT_DIR"
                cp --recursive /tmp/snapshot/* "$CARTESI_SNAPSHOT_DIR"
                exec cartesi-rollups-node

        env_file:
            - ${CARTESI_BIN_PATH}/node/default.env

    proxy:
        depends_on:
            validator:
                condition: service_healthy

    prompt:
        image: debian:bookworm-slim
        environment:
            PROMPT_TXT_02_GRAPHQL: "GraphQL running at http://localhost:${CARTESI_LISTEN_PORT}/graphql"
            PROMPT_TXT_03_INSPECT: "Inspect running at http://localhost:${CARTESI_LISTEN_PORT}/inspect/"
            PROMPT_TXT_08_METRICS: "Prometheus metrics at http://localhost:${CARTESI_LISTEN_PORT}/metrics"

    traefik-config-generator:
        environment:
            TRAEFIK_CONFIG_INSPECT_SERVER: |
                http:
                    routers:
                        inspect_server:
                            rule: "PathPrefix(`/inspect`)"
                            service: inspect_server
                    services:
                        inspect_server:
                            loadBalancer:
                                servers:
                                    - url: "http://validator:10000/inspect"
            TRAEFIK_CONFIG_GRAPHQL_SERVER: |
                http:
                    routers:
                        graphql_server:
                            rule: "PathPrefix(`/graphql`)"
                            service: graphql_server
                    services:
                        graphql_server:
                            loadBalancer:
                                servers:
                                    - url: "http://validator:10000/graphql"
            TRAEFIK_CONFIG_VALIDATOR_METRICS: |
                http:
                    routers:
                        validator_metrics:
                            rule: "PathPrefix(`/metrics`)"
                            service: validator_metrics
                    services:
                        validator_metrics:
                            loadBalancer:
                                servers:
                                    - url: "http://validator:10000/metrics"
