services:
    anvil:
        image: cartesi/sdk:0.12.0-alpha.3
        command:
            [
                "devnet",
                "--block-time",
                "${BLOCK_TIME:-5}",
                "${ANVIL_VERBOSITY:---silent}",
            ]
        healthcheck:
            test: ["CMD", "eth_isready"]
            interval: 10s
            timeout: 1s
            retries: 5
        environment:
            ANVIL_IP_ADDR: 0.0.0.0
        ports:
            - 8545:8545

    dapp_deployer:
        image: cartesi/rollups-node:devel
        restart: on-failure
        depends_on:
            validator:
                condition: service_started
        env_file:
            - ${CARTESI_BIN_PATH}/node/default.env
        command:
            - /bin/bash
            - -c
            - -x
            - |
                cartesi-rollups-cli app deploy                                                      \
                    --print-json                                                                    \
                    --postgres-endpoint "$$CARTESI_POSTGRES_ENDPOINT"                               \
                    --rpc-url "$$CARTESI_BLOCKCHAIN_HTTP_ENDPOINT"                                  \
                    --inputbox-block-number "$$CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER" \
                    --mnemonic "$$CARTESI_AUTH_MNEMONIC"                                            \
                    --epoch-length "$$CARTESI_EPOCH_LENGTH"                                         \
                    --app-factory "$$CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS"                 \
                    --authority-factory "$$CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS"             \
                    --app-owner "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"                        \
                    --template-path $$CARTESI_SNAPSHOT_DIR                                          \
                    --name "dapp"

    prompt:
        image: debian:bookworm-slim
        environment:
            PROMPT_TXT_01_ANVIL: "Anvil running at http://localhost:8545"

volumes:
    blockchain-data: {}
