services:
    database:
        image: postgres:16-alpine
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            - POSTGRES_PASSWORD=password
