sdk = "cartesi/sdk:devel"

[machine]
entrypoint = "rollup-init crun run --config /run/cruntime/config/config.json --bundle /run/cruntime app"

[drives.root]
builder = "docker"
#dockerfile = "cruntime.Dockerfile"
image = "cruntime"
format = "ext2"

[drives.crunconfig]
builder = "directory"
directory = "./config" # required
format = "sqfs"
mount = "/run/cruntime/config"

[drives.crunrootfs]
builder = "docker"
dockerfile = "jsdapp.Dockerfile"
context = "jsdapp"
format = "ext2"
mount = "/run/cruntime/rootfs"
