import { Healthcheck } from "../types/compose";

export const DB_ENV: Record<string, string | number | boolean | null> = {
    DB_PORT: 5432,
    DB_HOST: "database",
    DB_PASS: "password",
};

export const DEFAULT_HEALTHCHECK: Healthcheck = {
    start_period: "10s",
    start_interval: "200ms",
    interval: "10s",
    timeout: "1s",
    retries: 5,
};

export const DEFAULT_ENV: Record<string, string | number | boolean | null> = {
    CARTESI_LOG_LEVEL: "${CARTESI_LOG_LEVEL:-info}",
    // features
    CARTESI_FEATURE_INPUT_READER_ENABLED:
        "${CARTESI_FEATURE_INPUT_READER_ENABLED:-true}",
    CARTESI_FEATURE_CLAIM_SUBMISSION_ENABLED:
        "${CARTESI_FEATURE_CLAIM_SUBMISSION_ENABLED:-true}",
    CARTESI_FEATURE_MACHINE_HASH_CHECK_ENABLED:
        "${CARTESI_FEATURE_MACHINE_HASH_CHECK_ENABLED:-true}",
    CARTESI_SNAPSHOTS_DIR: "/var/lib/cartesi-rollups-node/snapshots",
    // rollups
    CARTESI_EVM_READER_RETRY_POLICY_MAX_RETRIES:
        "${CARTESI_EVM_READER_RETRY_POLICY_MAX_RETRIES:-3}",
    CARTESI_EVM_READER_RETRY_POLICY_MAX_DELAY:
        "${CARTESI_EVM_READER_RETRY_POLICY_MAX_DELAY:-3}",
    CARTESI_ADVANCER_POLLING_INTERVAL:
        "${CARTESI_ADVANCER_POLLING_INTERVAL:-3}",
    CARTESI_VALIDATOR_POLLING_INTERVAL:
        "${CARTESI_VALIDATOR_POLLING_INTERVAL:-3}",
    CARTESI_CLAIMER_POLLING_INTERVAL: "${CARTESI_CLAIMER_POLLING_INTERVAL:-3}",
    CARTESI_MAX_STARTUP_TIME: "${CARTESI_MAX_STARTUP_TIME:-15}",
    // blockchain
    CARTESI_BLOCKCHAIN_ID: "${CARTESI_BLOCKCHAIN_ID:-13370}",
    CARTESI_BLOCKCHAIN_HTTP_ENDPOINT:
        "${CARTESI_BLOCKCHAIN_HTTP_ENDPOINT:-http://anvil:8545}",
    CARTESI_BLOCKCHAIN_WS_ENDPOINT:
        "${CARTESI_BLOCKCHAIN_WS_ENDPOINT:-ws://anvil:8545}",
    CARTESI_BLOCKCHAIN_DEFAULT_BLOCK:
        "${CARTESI_BLOCKCHAIN_DEFAULT_BLOCK:-latest}",
    // contracts
    CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS:
        "${CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS:-0x26E758238CB6eC5aB70ce0dd52aF2d7b82e1972E}",
    CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS:
        "${CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS:-0x5a3368b30174d389aFd205a46bAd35BBE6709b8a}",
    CARTESI_CONTRACTS_INPUT_BOX_ADDRESS:
        "${CARTESI_CONTRACTS_INPUT_BOX_ADDRESS:-0x1b51e2992A2755Ba4D6F7094032DF91991a0Cfac}",
    CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS:
        "${CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS:-0x870240e83b1181b419f18303D4ccC56574De2931}",
    CARTESI_CONTRACTS_DAVE_APP_FACTORY_ADDRESS:
        "${CARTESI_CONTRACTS_DAVE_APP_FACTORY_ADDRESS:-0x81dfc08498B86be7659eFD66702DB539DD534c9f}",
    // auth
    CARTESI_AUTH_MNEMONIC:
        "${CARTESI_AUTH_MNEMONIC:-test test test test test test test test test test test junk}",
    // postgres
    CARTESI_DATABASE_CONNECTION: `postgres://postgres:${DB_ENV.DB_PASS}@${DB_ENV.DB_HOST}:${DB_ENV.DB_PORT}/rollupsdb?sslmode=disable`,
};
