services:
    database:
        image: ${CARTESI_SDK_DATABASE_IMAGE}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5
        environment:
            - POSTGRES_PASSWORD=password
