x-explorer_db_env: &explorer_db_env
    DB_NAME: explorer
    DB_PORT: 5432
    DB_HOST: database
    DB_PASS: password

configs:
    explorer_api_proxy:
        content: |
            http:
                routers:
                    explorer-api:
                        rule: "PathPrefix(`/explorer-api`)"
                        middlewares:
                            - "remove-explorer-api-prefix"
                        service: explorer-api
                middlewares:
                    remove-explorer-api-prefix:
                        replacePathRegex:
                            regex: "^/explorer-api/(.*)"
                            replacement: "/$1"
                services:
                    explorer-api:
                        loadBalancer:
                            servers:
                                - url: "http://explorer_api:4350"
    explorer_proxy:
        content: |
            http:
                routers:
                    explorer:
                        rule: "PathPrefix(`/explorer`)"
                        service: explorer
                services:
                    explorer:
                        loadBalancer:
                            servers:
                                - url: "http://explorer:3000"

services:
    explorer_api:
        image: cartesi/rollups-explorer-api:1.0.0
        environment:
            <<: *explorer_db_env
            GQL_PORT: 4350
        expose:
            - 4350
        command: ["sqd", "serve:prod"]
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--spider",
                    "-q",
                    "http://127.0.0.1:4350/graphql?query=%7B__typename%7D",
                ]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5
        depends_on:
            database:
                condition: service_healthy

    squid_processor:
        image: cartesi/rollups-explorer-api:1.0.0
        environment:
            <<: *explorer_db_env
            CHAIN_IDS: ${CARTESI_BLOCKCHAIN_ID:-13370}
            RPC_URL_13370: ${RPC_URL:-http://anvil:8545}
            BLOCK_CONFIRMATIONS_13370: 0
            GENESIS_BLOCK_13370: 1
        command: ["sqd", "process:prod"]
        depends_on:
            database:
                condition: service_healthy

    explorer:
        image: cartesi/rollups-explorer:1.3.3
        environment:
            NODE_RPC_URL: "http://127.0.0.1:${CARTESI_LISTEN_PORT:-6751}/anvil"
            EXPLORER_API_URL: "http://127.0.0.1:${CARTESI_LISTEN_PORT:-6751}/explorer-api/graphql"
        expose:
            - 3000
        depends_on:
            database:
                condition: service_healthy

    proxy:
        configs:
            - source: explorer_proxy
              target: /etc/traefik/conf.d/explorer.yaml
            - source: explorer_api_proxy
              target: /etc/traefik/conf.d/explorer-api.yaml
