services:
    rollups-node:
        image: cartesi/rollups-runtime:${CARTESI_SDK_VERSION}
        depends_on:
            database:
                condition: service_healthy
            anvil:
                condition: service_healthy
        expose:
            - "10000"
            - "10011"
            - "10012"
        healthcheck:
            test: ["CMD", "curl", "-fsS", "http://127.0.0.1:10000/livez"]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5
        command: ["cartesi-rollups-node"]
        env_file:
            - ${CARTESI_BIN_PATH}/compose/default.env
        volumes:
            - snapshots:/var/lib/cartesi-rollups-node/snapshots

    proxy:
        volumes:
            - ./proxy/rollups-node.yaml:/etc/traefik/conf.d/rollups-node.yaml

volumes:
    snapshots:
