configs:
    passkey_server_proxy:
        content: |
            http:
                routers:
                    passkey-server:
                        rule: "PathPrefix(`/passkey`)"
                        middlewares:
                            - "remove-passkey-server-prefix"
                        service: passkey-server
                middlewares:
                    remove-passkey-server-prefix:
                        replacePathRegex:
                            regex: "^/passkey/(.*)"
                            replacement: "/$1"
                services:
                    passkey-server:
                        loadBalancer:
                            servers:
                                - url: "http://passkey-server:3000"

services:
    passkey-server:
        image: ${CARTESI_SDK_IMAGE}
        command: ["passkey-server"]
        healthcheck:
            test: ["CMD", "curl", "-fsS", "http://127.0.0.1:3000/health"]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5

    proxy:
        configs:
            - source: passkey_server_proxy
              target: /etc/traefik/conf.d/passkey-server.yaml
