services:
    proxy:
        image: docker.io/traefik:v3.5.4@sha256:fa528d4565c8c279328c12d466325ee0f65804a75bcdbef737290664ad971d68
        healthcheck:
            test: ["CMD", "traefik", "healthcheck", "--ping"]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5
        command:
            [
                "--ping=true",
                "--entryPoints.web.address=:8088",
                "--entryPoints.traefik.address=:8080",
                "--metrics.prometheus=true",
                "--metrics.prometheus.addServicesLabels=true",
                "--providers.file.directory=/etc/traefik/conf.d",
                "--providers.file.watch=true",
                "--log",
                "--log.level=INFO",
            ]
        ports:
            - ${CARTESI_LISTEN_PORT:-6751}:8088
