import { anvil } from "viem/chains";
import type { CartesiEnvironmentVariables } from "../base.js";
import {
    daveAppFactoryAddress,
    inputBoxAddress,
    selfHostedApplicationFactoryAddress,
} from "../contracts.js";
import type { ComposeFile, Config, Service } from "../types/compose.js";
import { DEFAULT_HEALTHCHECK } from "./common.js";

export type ServiceOptions = {
    cpus?: number;
    databaseHost?: string;
    databasePort?: number;
    databasePassword: string;
    defaultBlock?: "latest" | "safe" | "pending" | "finalized";
    forkChainId?: number;
    logLevel?: "info" | "debug" | "warn" | "error" | "fatal";
    memory?: number;
    mnemonic?: string;
    imageTag?: string;
    prt?: boolean;
    cartesiEnvironmentVariables?: CartesiEnvironmentVariables;
};

/**
 * A list of allowed environment variables
 * that can be passed to the rollups node service.
 * A number of environment variables are rule out to avoid confusion e.g. CORS, FEATURE Enablement, etc.
 */
export const nodeAllowedEnvironmentVariables = [
    "CARTESI_AUTH_MNEMONIC",
    "CARTESI_AUTH_MNEMONIC_ACCOUNT_INDEX",
    "CARTESI_BLOCKCHAIN_DEFAULT_BLOCK",
    "CARTESI_BLOCKCHAIN_HTTP_AUTHORIZATION",
    "CARTESI_BLOCKCHAIN_HTTP_ENDPOINT",
    "CARTESI_BLOCKCHAIN_ID",
    "CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS",
    "CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS",
    "CARTESI_CONTRACTS_DAVE_APP_FACTORY_ADDRESS",
    "CARTESI_CONTRACTS_INPUT_BOX_ADDRESS",
    "CARTESI_CONTRACTS_QUORUM_FACTORY_ADDRESS",
    "CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS",
    "CARTESI_DATABASE_CONNECTION",
    "CARTESI_LOG_LEVEL",
    "CARTESI_LOG_LEVEL_ADVANCER",
    "CARTESI_LOG_LEVEL_CLAIMER",
    "CARTESI_LOG_LEVEL_EVM_READER",
    "CARTESI_LOG_LEVEL_JSONRPC_API",
    "CARTESI_LOG_LEVEL_PRT",
    "CARTESI_LOG_LEVEL_VALIDATOR",
    "CARTESI_JSONRPC_MACHINE_LOG_LEVEL",
    "CARTESI_SNAPSHOTS_DIR",
] as const;

type NodeAllowedEnvironmentVars = Partial<
    Record<(typeof nodeAllowedEnvironmentVariables)[number], string>
>;

/**
 *  Returns a subset of the provided environment variables that are allowed
 * to be passed to the rollups node service.
 *  If no environment variables are provided, an empty object is returned.
 *  @param cartesiVars - An object containing environment variables to filter.
 *  @returns An object containing only the allowed environment variables.
 * @param cartesiVars
 * @returns
 */
export const getNodeAllowedVariables = (
    cartesiVars?: CartesiEnvironmentVariables,
): NodeAllowedEnvironmentVars => {
    const allowedVars = nodeAllowedEnvironmentVariables.reduce(
        (acc, variableName) => {
            const value = cartesiVars?.[variableName];

            if (value !== undefined && value !== null) {
                acc[variableName] = value;
            }

            return acc;
        },
        {} as NodeAllowedEnvironmentVars,
    );

    return allowedVars;
};

// Rollups Node service
const service = (options: ServiceOptions): Service => {
    const databasePassword = options.databasePassword;
    const databaseHost = options.databaseHost ?? "database";
    const databasePort = options.databasePort ?? 5432;
    const defaultBlock = options.defaultBlock ?? "latest";
    const imageTag = options.imageTag ?? "latest";
    const logLevel = options.logLevel ?? "info";
    const mnemonic =
        options.mnemonic ??
        "test test test test test test test test test test test junk";
    const prt = options.prt ?? false;
    const chainId = (options.forkChainId ??
        31337) as keyof typeof daveAppFactoryAddress;

    let chainDaveAppFactoryAddress: string | undefined;
    if (prt) {
        chainDaveAppFactoryAddress = daveAppFactoryAddress[chainId];
        if (!chainDaveAppFactoryAddress) {
            throw new Error(`Unsupported fork chain ${chainId}`);
        }
    }

    const defaultVars = {
        CARTESI_AUTH_MNEMONIC: mnemonic,
        // First account generated by the devnet test mnemonic 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
        CARTESI_AUTH_MNEMONIC_ACCOUNT_INDEX: "0",
        CARTESI_BLOCKCHAIN_DEFAULT_BLOCK: defaultBlock,
        CARTESI_BLOCKCHAIN_HTTP_ENDPOINT: "http://anvil:8545",
        CARTESI_BLOCKCHAIN_ID: anvil.id.toString(),
        ...(chainDaveAppFactoryAddress && {
            CARTESI_CONTRACTS_DAVE_APP_FACTORY_ADDRESS:
                chainDaveAppFactoryAddress,
        }),
        CARTESI_CONTRACTS_INPUT_BOX_ADDRESS: inputBoxAddress,
        CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS:
            selfHostedApplicationFactoryAddress,
        CARTESI_DATABASE_CONNECTION: `postgres://postgres:${databasePassword}@${databaseHost}:${databasePort}/rollupsdb?sslmode=disable`,
        CARTESI_LOG_LEVEL: logLevel,
        CARTESI_SNAPSHOTS_DIR: "/var/lib/cartesi-rollups-node/snapshots",
    };

    const hostVars = getNodeAllowedVariables(
        options.cartesiEnvironmentVariables,
    );

    // Merge default and host environment variables, with host variables taking precedence
    // further to the right of the parameter list the higher the precedence
    // TODO: Here or somewhere else; Add other variables with precedence rules, e.g. command line > <config>.toml > host environment > default
    const environmentVariables = Object.assign({}, defaultVars, hostVars);

    return {
        image: `cartesi/rollups-runtime:${imageTag}`,
        init: true,
        depends_on: {
            database: { condition: "service_healthy" },
            anvil: { condition: "service_healthy" },
        },
        deploy: {
            resources: {
                limits: {
                    cpus:
                        options.cpus !== undefined
                            ? options.cpus.toString()
                            : undefined,
                    memory:
                        options.memory !== undefined
                            ? `${options.memory.toString()}M`
                            : undefined,
                },
            },
        },
        expose: ["10000", "10011", "10012"],
        healthcheck: {
            ...DEFAULT_HEALTHCHECK,
            test: ["CMD", "curl", "-fsS", "http://127.0.0.1:10000/livez"],
        },
        command: ["cartesi-rollups-node"],
        environment: {
            ...environmentVariables,
        },
        volumes: ["./.cartesi:/var/lib/cartesi-rollups-node/snapshots:ro"],
    };
};

// Rollups Node proxy configuration
const proxy = (): Config => {
    return {
        name: "rollups-node-proxy",
        content: `
http:
    routers:
        inspect_server:
            rule: "PathPrefix(\`/inspect\`)"
            middlewares:
                - "cors"
            service: inspect_server
        rpc_server:
            rule: "PathPrefix(\`/rpc\`)"
            middlewares:
                - "cors"
            service: rpc_server
    middlewares:
        cors:
            headers:
                accessControlAllowMethods:
                    - GET
                    - OPTIONS
                    - POST
                accessControlAllowHeaders:
                    - "Origin"
                    - "Content-Type"
                    - "Accept"
                accessControlAllowOriginList:
                    - "*"
                accessControlMaxAge: 86400
                addVaryHeader: true
    services:
        inspect_server:
            loadBalancer:
                servers:
                    - url: "http://rollups_node:10012"
        rpc_server:
            loadBalancer:
                servers:
                    - url: "http://rollups_node:10011"
`,
    };
};

export default (options: ServiceOptions): ComposeFile => ({
    services: {
        proxy: {
            configs: [
                {
                    source: "rollups_node_proxy",
                    target: "/etc/traefik/conf.d/rollups-node.yaml",
                },
            ],
        },
        rollups_node: service(options),
    },
    configs: {
        rollups_node_proxy: proxy(),
    },
});
