import { createCartesiPublicClient } from "@cartesi/client";
import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { type ResultPromise, execa } from "execa";
import fs from "fs-extra";
import path from "node:path";
import pRetry, { AbortError } from "p-retry";
import tmp from "tmp";
import {
    type Address,
    createTestClient,
    http,
    parseEther,
    publicActions,
    walletActions,
} from "viem";
import { mnemonicToAccount } from "viem/accounts";
import { DEVNET_MNEMONIC } from "../../../src/compose/node";
import {
    erc20PortalAbi,
    erc20PortalAddress,
    testUsdcAbi,
    testUsdcAddress,
    testUsdWithdrawalOutputBuilderAddress,
} from "../../../src/contracts";
import { replayStorePath } from "../../../src/commands/withdraw";
import {
    execNodeCommand,
    getDeployments,
    getProjectPort,
    proveAccountsDrive,
    stopEnvironment,
} from "../../../src/exec/rollups";
import { cartesi } from "../../../src/wallet";
import { TEST_RUNTIME_VERSION, TEST_SDK } from "../config";

/**
 * Covers the fund recovery of a foreclosed application end to end: a deposit
 * that was not finalized is refunded, and the finalized balances, kept by the
 * application in its accounts drive, are withdrawn from proofs generated by
 * replaying the application.
 *
 * The runtime must ship a rollups node with the refund command, as the
 * default SDK does.
 *
 * Inputs: alice (0), bob (1) and erin (2) are finalized in epoch 0; carol (3)
 * and dave (4) stay in the open epoch 1 and are refunded.
 */

const EPOCH_LENGTH = 720;
const TIMEOUT = 30 * 60 * 1000;

const cliPath = path.join(__dirname, "..", "..", "..", "dist", "index.js");
const fixture = path.join(__dirname, "fixtures", "erc20-withdrawal");
const projectName = `recovery-${process.pid}`;

const account = (addressIndex: number) =>
    mnemonicToAccount(DEVNET_MNEMONIC, { addressIndex }).address;
const alice = account(0);
const bob = account(2);
const carol = account(3);
const dave = account(4);
const erin = account(5);

// the guardian comes from a mnemonic the node doesn't sign with
const guardianMnemonic =
    "legal winner thank year wave sausage worth useful legal winner thank yellow";
const guardian = mnemonicToAccount(guardianMnemonic).address;

const amounts = { alice: 100n, bob: 50n, carol: 25n, dave: 15n, erin: 10n };

const count = (text: string, part: string) => text.split(part).length - 1;

/**
 * Layout of the accounts drive in the built machine: its size in log2 of the
 * number of 32-byte accounts, and its start as a multiple of its size
 */
const accountsDriveLayout = async (appDir: string, driveIndex: number) => {
    const { config } = await fs.readJson(
        path.join(appDir, ".cartesi", "image", "config.json"),
    );
    const { start, length } = config.flash_drive[driveIndex];
    const log2Length = Math.log2(length);
    expect(Number.isInteger(log2Length)).toBe(true);
    expect(start % length).toBe(0);
    return {
        accountsDriveStartIndex: start / length,
        log2MaxNumOfAccounts: log2Length - 5,
    };
};

describe("fund recovery", () => {
    let appDir: string;
    let cleanup: () => void;
    let run: ResultPromise | undefined;
    let application: Address;
    let anvil: Awaited<ReturnType<typeof createAnvilClient>>;
    let node: ReturnType<typeof createCartesiPublicClient>;

    const cli = (args: string[], env?: Record<string, string>) =>
        execa("node", [cliPath, ...args, "--project-name", projectName], {
            all: true,
            cwd: appDir,
            env,
            reject: false,
        });

    // temporary files written into the node container with mktemp
    const nodeTempFiles = async () =>
        Number(
            await execNodeCommand({
                command: ["sh", "-c", "ls /tmp/tmp.* 2>/dev/null | wc -l"],
                projectName,
            }),
        );

    const createAnvilClient = async () => {
        const host = await getProjectPort({ projectName });
        return createTestClient({
            chain: cartesi,
            mode: "anvil",
            transport: http(`http://${host}/anvil`),
            pollingInterval: 200,
        })
            .extend(publicActions)
            .extend(walletActions);
    };

    const usdcBalance = (owner: Address) =>
        anvil.readContract({
            abi: testUsdcAbi,
            address: testUsdcAddress,
            args: [owner],
            functionName: "balanceOf",
        });

    const deposit = async (from: Address, amount: bigint) => {
        await anvil.impersonateAccount({ address: from });
        const transactions = [
            () =>
                anvil.writeContract({
                    abi: testUsdcAbi,
                    account: from,
                    address: testUsdcAddress,
                    args: [amount],
                    functionName: "mint",
                }),
            () =>
                anvil.writeContract({
                    abi: testUsdcAbi,
                    account: from,
                    address: testUsdcAddress,
                    args: [erc20PortalAddress, amount],
                    functionName: "approve",
                }),
            () =>
                anvil.writeContract({
                    abi: erc20PortalAbi,
                    account: from,
                    address: erc20PortalAddress,
                    args: [testUsdcAddress, application, amount, "0x"],
                    functionName: "depositErc20Tokens",
                }),
        ];
        for (const transaction of transactions) {
            const hash = await transaction();
            const receipt = await anvil.waitForTransactionReceipt({ hash });
            expect(receipt.status).toBe("success");
        }
    };

    const waitFor = <T>(fn: () => Promise<T>, retries = 120) =>
        pRetry(fn, { retries, minTimeout: 1000, maxTimeout: 1000 });

    beforeAll(async () => {
        const dir = tmp.dirSync({ unsafeCleanup: true });
        cleanup = dir.removeCallback;
        appDir = path.join(dir.name, "erc20-withdrawal");
        await fs.copy(fixture, appDir);
        await fs.writeFile(
            path.join(appDir, "cartesi.toml"),
            `sdk = "${TEST_SDK}"

[machine.env]
TRUSTED_ERC20_PORTAL = "${erc20PortalAddress}"
TRUSTED_ERC20_TOKEN = "${testUsdcAddress}"

[drives.accounts]
builder = "empty"
format = "raw"
size = "4MB"
mount = false
user = "dapp"
`,
        );

        console.log("! Building the erc20-withdrawal application...");
        const build = await execa("node", [cliPath, "build"], {
            all: true,
            cwd: appDir,
            reject: false,
        });
        expect(build.exitCode, build.all).toBe(0);
        console.log("✓ Built the erc20-withdrawal application");

        // the accounts drive follows the root drive
        const layout = await accountsDriveLayout(appDir, 1);
        await fs.appendFile(
            path.join(appDir, "cartesi.toml"),
            `
[withdrawal.config]
guardian = "${guardian}"
log2_leaves_per_account = 0
log2_max_num_of_accounts = ${layout.log2MaxNumOfAccounts}
accounts_drive_start_index = ${layout.accountsDriveStartIndex}
withdrawal_output_builder = "${testUsdWithdrawalOutputBuilderAddress}"
`,
        );

        // without a terminal the environment runs in the foreground
        console.log(`! Starting the environment ${projectName}...`);
        run = execa(
            "node",
            [
                cliPath,
                "run",
                "--project-name",
                projectName,
                "--runtime-version",
                TEST_RUNTIME_VERSION,
                "--epoch-length",
                EPOCH_LENGTH.toString(),
                "--block-time",
                "1",
            ],
            {
                all: true,
                cwd: appDir,
                reject: false,
            },
        );

        application = await waitFor(async () => {
            if (run && run.nodeChildProcess.exitCode !== null) {
                const { all } = await run;
                throw new AbortError(`cartesi run exited\n${all}`);
            }
            const [deployment] = await getDeployments({ projectName });
            if (!deployment) {
                throw new Error("application not deployed yet");
            }
            return deployment.address;
        }, 600);
        console.log(`✓ Application deployed at ${application}`);

        anvil = await createAnvilClient();
        const host = await getProjectPort({ projectName });
        node = createCartesiPublicClient({
            transport: http(`http://${host}/rpc`),
        });
    }, TIMEOUT);

    afterAll(async () => {
        await stopEnvironment({ projectName }).catch(() => undefined);
        run?.kill();
        cleanup?.();
    }, TIMEOUT);

    it(
        "should finalize the first deposits",
        async () => {
            await deposit(alice, amounts.alice);
            await deposit(bob, amounts.bob);
            await deposit(erin, amounts.erin);

            // close the first epoch and wait for its claim to be accepted
            await anvil.mine({ blocks: EPOCH_LENGTH });
            console.log("! Waiting for epoch 0 to be accepted...");
            const epochIndex = await waitFor(() =>
                node.getLastAcceptedEpochIndex({ application }),
            );
            expect(epochIndex).toBe(0n);
            console.log("✓ Epoch 0 accepted");
            expect(await usdcBalance(alice)).toBe(0n);

            // these stay in the open epoch, never finalized
            await deposit(carol, amounts.carol);
            await deposit(dave, amounts.dave);
            await waitFor(() => node.getInput({ application, inputIndex: 4n }));
        },
        TIMEOUT,
    );

    describe("before the foreclosure", () => {
        it(
            "should pass the node's NotForeclosed error through on refund",
            async () => {
                const refund = await cli(["refund", "3", "--yes"]);
                expect(refund.exitCode).not.toBe(0);
                expect(refund.all).toContain("NotForeclosed");
            },
            TIMEOUT,
        );

        it(
            "should not withdraw from an application that isn't foreclosed",
            async () => {
                const withdraw = await cli([
                    "withdraw",
                    "--account",
                    alice,
                    "--yes",
                ]);
                expect(withdraw.exitCode).not.toBe(0);
                expect(withdraw.all).toContain("is not foreclosed");
            },
            TIMEOUT,
        );

        it(
            "should point to --input-file for an input the node doesn't have",
            async () => {
                const refund = await cli(["refund", "99", "--yes"]);
                expect(refund.exitCode).not.toBe(0);
                expect(refund.all).toContain("Input 99 not found in the node");
            },
            TIMEOUT,
        );
    });

    it(
        "should foreclose as a guardian outside the node signer",
        async () => {
            await anvil.setBalance({
                address: guardian,
                value: parseEther("1"),
            });
            const foreclose = await cli(["foreclose", "--yes"], {
                CARTESI_AUTH_MNEMONIC: guardianMnemonic,
            });
            expect(foreclose.exitCode, foreclose.all).toBe(0);
        },
        TIMEOUT,
    );

    describe("after the foreclosure", () => {
        it(
            "should not withdraw with a proof file before the drive root is proven",
            async () => {
                const proofFile = path.join(appDir, "unused-proof.json");
                await fs.writeFile(proofFile, "{}");
                const withdraw = await cli([
                    "withdraw",
                    "--proof-file",
                    proofFile,
                    "--yes",
                ]);
                expect(withdraw.exitCode).not.toBe(0);
                expect(withdraw.all).toContain("isn't proven yet");
            },
            TIMEOUT,
        );

        it(
            "should refund a deposit that was not finalized",
            async () => {
                expect(await usdcBalance(carol)).toBe(0n);
                const refund = await cli(["refund", "3", "--yes", "--json"]);
                expect(refund.exitCode, refund.all).toBe(0);
                expect(JSON.parse(refund.stdout)).toMatchObject({
                    input_index: "3",
                });
                expect(await usdcBalance(carol)).toBe(amounts.carol);
            },
            TIMEOUT,
        );

        it(
            "should refund with the input bytes from a file",
            async () => {
                const { rawData } = await node.getInput({
                    application,
                    inputIndex: 4n,
                });
                const inputFile = path.join(appDir, "dave-input.hex");
                await fs.writeFile(inputFile, rawData);
                expect(await usdcBalance(dave)).toBe(0n);
                const refund = await cli([
                    "refund",
                    "4",
                    "--input-file",
                    inputFile,
                    "--yes",
                ]);
                expect(refund.exitCode, refund.all).toBe(0);
                expect(await usdcBalance(dave)).toBe(amounts.dave);
                expect(await nodeTempFiles()).toBe(0);
            },
            TIMEOUT,
        );

        it(
            "should fail to prove an account that isn't in the drive",
            async () => {
                const withdraw = await cli([
                    "withdraw",
                    "--account",
                    carol,
                    "--yes",
                ]);
                expect(withdraw.exitCode).not.toBe(0);
                expect(withdraw.all).toContain(
                    `Failed to generate the proofs of ${carol}`,
                );
            },
            TIMEOUT,
        );

        it(
            "should withdraw the finalized balance of an account",
            async () => {
                expect(await usdcBalance(alice)).toBe(0n);
                const withdraw = await cli([
                    "withdraw",
                    "--account",
                    alice,
                    "--yes",
                    "--json",
                ]);
                expect(withdraw.exitCode, withdraw.all).toBe(0);
                // carol's attempt already replayed the finalized epoch
                expect(withdraw.stderr).toContain("Using the machine replayed");
                // the drive root is proven first, then the withdrawal
                expect(count(withdraw.stderr, "Transaction hash:")).toBe(2);
                const result = JSON.parse(withdraw.stdout);
                expect(result.application_address.toLowerCase()).toBe(
                    application.toLowerCase(),
                );
                expect(await usdcBalance(alice)).toBe(amounts.alice);
            },
            TIMEOUT,
        );

        it(
            "should prove the drive root only once",
            async () => {
                expect(await usdcBalance(bob)).toBe(0n);
                const withdraw = await cli([
                    "withdraw",
                    "--account",
                    bob,
                    "--yes",
                    "--json",
                ]);
                expect(withdraw.exitCode, withdraw.all).toBe(0);
                expect(withdraw.stderr).toContain("Using the machine replayed");
                expect(count(withdraw.stderr, "Transaction hash:")).toBe(1);
                expect(await usdcBalance(bob)).toBe(amounts.bob);
            },
            TIMEOUT,
        );

        it(
            "should withdraw with a proof file",
            async () => {
                // generate erin's proof from the cached replay, as an outside
                // tool would, and withdraw through the file path
                const { withdrawalConfig } = await node.getApplication({
                    application,
                });
                const proof = await proveAccountsDrive({
                    account: erin,
                    driveConfig: withdrawalConfig,
                    outDir: `/tmp/recovery-test/${erin}`,
                    projectName,
                    snapshot: replayStorePath(application, 0n),
                });
                const proofFile = path.join(appDir, "erin-proof.json");
                await fs.writeFile(
                    proofFile,
                    await execNodeCommand({
                        command: ["cat", proof.withdrawProofFile],
                        projectName,
                    }),
                );

                expect(await usdcBalance(erin)).toBe(0n);
                const withdraw = await cli([
                    "withdraw",
                    "--proof-file",
                    proofFile,
                    "--yes",
                ]);
                expect(withdraw.exitCode, withdraw.all).toBe(0);
                expect(await usdcBalance(erin)).toBe(amounts.erin);
                expect(await nodeTempFiles()).toBe(0);
            },
            TIMEOUT,
        );
    });

    it("should reject --account together with --proof-file", async () => {
        const withdraw = await cli([
            "withdraw",
            "--account",
            alice,
            "--proof-file",
            "proof.json",
        ]);
        expect(withdraw.exitCode).not.toBe(0);
        expect(withdraw.all).toContain("cannot be used with option");
    });
});
