import { createCartesiPublicClient } from "@cartesi/client";
import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { type ResultPromise, execa } from "execa";
import fs from "fs-extra";
import path from "node:path";
import pRetry, { AbortError } from "p-retry";
import tmp from "tmp";
import {
    type Address,
    createTestClient,
    http,
    publicActions,
    walletActions,
} from "viem";
import { mnemonicToAccount } from "viem/accounts";
import { DEVNET_MNEMONIC } from "../../../src/compose/node";
import {
    erc20PortalAbi,
    erc20PortalAddress,
    testUsdcAbi,
    testUsdcAddress,
    testUsdWithdrawalOutputBuilderAddress,
} from "../../../src/contracts";
import {
    getDeployments,
    getProjectPort,
    stopEnvironment,
} from "../../../src/exec/rollups";
import { cartesi } from "../../../src/wallet";
import { TEST_RUNTIME_VERSION, TEST_SDK } from "../config";

/**
 * Covers the fund recovery of a foreclosed application end to end: a deposit
 * that was not finalized is refunded, and the finalized balances, kept by the
 * application in its accounts drive, are withdrawn from proofs generated by
 * replaying the application.
 *
 * The runtime must ship a rollups node with the refund command, e.g. the
 * images built from rollups-node#798 with CARTESI_TEST_SDK=cartesi/sdk:798 and
 * CARTESI_TEST_RUNTIME_VERSION=798.
 */

const EPOCH_LENGTH = 720;
const TIMEOUT = 30 * 60 * 1000;

const cliPath = path.join(__dirname, "..", "..", "..", "dist", "index.js");
const fixture = path.join(__dirname, "fixtures", "erc20-withdrawal");
const projectName = `recovery-${process.pid}`;

const account = (addressIndex: number) =>
    mnemonicToAccount(DEVNET_MNEMONIC, { addressIndex }).address;
const alice = account(0);
const guardian = account(1);
const bob = account(2);
const carol = account(3);

const amounts = { alice: 100n, bob: 50n, carol: 25n };

/**
 * Layout of the accounts drive in the built machine: its size in log2 of the
 * number of 32-byte accounts, and its start as a multiple of its size
 */
const accountsDriveLayout = async (appDir: string, driveIndex: number) => {
    const { config } = await fs.readJson(
        path.join(appDir, ".cartesi", "image", "config.json"),
    );
    const { start, length } = config.flash_drive[driveIndex];
    const log2Length = Math.log2(length);
    expect(Number.isInteger(log2Length)).toBe(true);
    expect(start % length).toBe(0);
    return {
        accountsDriveStartIndex: start / length,
        log2MaxNumOfAccounts: log2Length - 5,
    };
};

describe("fund recovery", () => {
    let appDir: string;
    let cleanup: () => void;
    let run: ResultPromise | undefined;
    let application: Address;
    let anvil: Awaited<ReturnType<typeof createAnvilClient>>;
    let node: ReturnType<typeof createCartesiPublicClient>;

    const cli = (args: string[]) =>
        execa("node", [cliPath, ...args, "--project-name", projectName], {
            all: true,
            cwd: appDir,
            reject: false,
        });

    const createAnvilClient = async () => {
        const host = await getProjectPort({ projectName });
        return createTestClient({
            chain: cartesi,
            mode: "anvil",
            transport: http(`http://${host}/anvil`),
            pollingInterval: 200,
        })
            .extend(publicActions)
            .extend(walletActions);
    };

    const usdcBalance = (owner: Address) =>
        anvil.readContract({
            abi: testUsdcAbi,
            address: testUsdcAddress,
            args: [owner],
            functionName: "balanceOf",
        });

    const deposit = async (from: Address, amount: bigint) => {
        await anvil.impersonateAccount({ address: from });
        const transactions = [
            () =>
                anvil.writeContract({
                    abi: testUsdcAbi,
                    account: from,
                    address: testUsdcAddress,
                    args: [amount],
                    functionName: "mint",
                }),
            () =>
                anvil.writeContract({
                    abi: testUsdcAbi,
                    account: from,
                    address: testUsdcAddress,
                    args: [erc20PortalAddress, amount],
                    functionName: "approve",
                }),
            () =>
                anvil.writeContract({
                    abi: erc20PortalAbi,
                    account: from,
                    address: erc20PortalAddress,
                    args: [testUsdcAddress, application, amount, "0x"],
                    functionName: "depositErc20Tokens",
                }),
        ];
        for (const transaction of transactions) {
            const hash = await transaction();
            const receipt = await anvil.waitForTransactionReceipt({ hash });
            expect(receipt.status).toBe("success");
        }
    };

    const waitFor = <T>(fn: () => Promise<T>, retries = 120) =>
        pRetry(fn, { retries, minTimeout: 1000, maxTimeout: 1000 });

    beforeAll(async () => {
        const dir = tmp.dirSync({ unsafeCleanup: true });
        cleanup = dir.removeCallback;
        appDir = path.join(dir.name, "erc20-withdrawal");
        await fs.copy(fixture, appDir);
        await fs.writeFile(
            path.join(appDir, "cartesi.toml"),
            `sdk = "${TEST_SDK}"

[machine.env]
TRUSTED_ERC20_PORTAL = "${erc20PortalAddress}"
TRUSTED_ERC20_TOKEN = "${testUsdcAddress}"

[drives.accounts]
builder = "empty"
format = "raw"
size = "4MB"
mount = false
user = "dapp"
`,
        );

        console.log("! Building the erc20-withdrawal application...");
        const build = await execa("node", [cliPath, "build"], {
            all: true,
            cwd: appDir,
            reject: false,
        });
        expect(build.exitCode, build.all).toBe(0);
        console.log("✓ Built the erc20-withdrawal application");

        // the accounts drive follows the root drive
        const layout = await accountsDriveLayout(appDir, 1);
        await fs.appendFile(
            path.join(appDir, "cartesi.toml"),
            `
[withdrawal.config]
guardian = "${guardian}"
log2_leaves_per_account = 0
log2_max_num_of_accounts = ${layout.log2MaxNumOfAccounts}
accounts_drive_start_index = ${layout.accountsDriveStartIndex}
withdrawal_output_builder = "${testUsdWithdrawalOutputBuilderAddress}"
`,
        );

        // without a terminal the environment runs in the foreground
        console.log(`! Starting the environment ${projectName}...`);
        run = execa(
            "node",
            [
                cliPath,
                "run",
                "--project-name",
                projectName,
                "--runtime-version",
                TEST_RUNTIME_VERSION,
                "--epoch-length",
                EPOCH_LENGTH.toString(),
                "--block-time",
                "1",
            ],
            {
                all: true,
                cwd: appDir,
                reject: false,
            },
        );

        application = await waitFor(async () => {
            if (run && run.nodeChildProcess.exitCode !== null) {
                const { all } = await run;
                throw new AbortError(`cartesi run exited\n${all}`);
            }
            const [deployment] = await getDeployments({ projectName });
            if (!deployment) {
                throw new Error("application not deployed yet");
            }
            return deployment.address;
        }, 600);
        console.log(`✓ Application deployed at ${application}`);

        anvil = await createAnvilClient();
        const host = await getProjectPort({ projectName });
        node = createCartesiPublicClient({
            transport: http(`http://${host}/rpc`),
        });
    }, TIMEOUT);

    afterAll(async () => {
        await stopEnvironment({ projectName }).catch(() => undefined);
        run?.kill();
        cleanup?.();
    }, TIMEOUT);

    it(
        "should finalize the first deposits",
        async () => {
            await deposit(alice, amounts.alice);
            await deposit(bob, amounts.bob);

            // close the first epoch and wait for its claim to be accepted
            await anvil.mine({ blocks: EPOCH_LENGTH });
            console.log("! Waiting for epoch 0 to be accepted...");
            const epochIndex = await waitFor(() =>
                node.getLastAcceptedEpochIndex({ application }),
            );
            expect(epochIndex).toBe(0n);
            console.log("✓ Epoch 0 accepted");
            expect(await usdcBalance(alice)).toBe(0n);
        },
        TIMEOUT,
    );

    it(
        "should not refund before the application is foreclosed",
        async () => {
            await deposit(carol, amounts.carol);
            await waitFor(() => node.getInput({ application, inputIndex: 2n }));

            const refund = await cli(["refund", "2", "--yes"]);
            expect(refund.exitCode).not.toBe(0);
            expect(refund.all).toContain("NotForeclosed");
        },
        TIMEOUT,
    );

    it(
        "should foreclose signing as the guardian",
        async () => {
            const foreclose = await cli(["foreclose", "--yes"]);
            expect(foreclose.exitCode, foreclose.all).toBe(0);
        },
        TIMEOUT,
    );

    it(
        "should refund the deposit that was not finalized",
        async () => {
            expect(await usdcBalance(carol)).toBe(0n);
            const refund = await cli(["refund", "2", "--yes", "--json"]);
            expect(refund.exitCode, refund.all).toBe(0);
            expect(JSON.parse(refund.stdout)).toMatchObject({
                input_index: "2",
            });
            expect(await usdcBalance(carol)).toBe(amounts.carol);
        },
        TIMEOUT,
    );

    it(
        "should withdraw the finalized balance of an account",
        async () => {
            expect(await usdcBalance(alice)).toBe(0n);
            const withdraw = await cli([
                "withdraw",
                "--account",
                alice,
                "--yes",
                "--json",
            ]);
            expect(withdraw.exitCode, withdraw.all).toBe(0);
            expect(withdraw.stderr).toContain("Replayed");
            const result = JSON.parse(withdraw.stdout);
            expect(result.application_address.toLowerCase()).toBe(
                application.toLowerCase(),
            );
            expect(await usdcBalance(alice)).toBe(amounts.alice);
        },
        TIMEOUT,
    );

    it(
        "should reuse the replayed machine for another account",
        async () => {
            expect(await usdcBalance(bob)).toBe(0n);
            const withdraw = await cli([
                "withdraw",
                "--account",
                bob,
                "--yes",
                "--json",
            ]);
            expect(withdraw.exitCode, withdraw.all).toBe(0);
            expect(withdraw.stderr).toContain("Using the machine replayed");
            expect(await usdcBalance(bob)).toBe(amounts.bob);
        },
        TIMEOUT,
    );
});
