services:
    graphql:
        image: ${CARTESI_SDK_IMAGE}
        environment:
            CARTESI_GRAPHQL_DATABASE_CONNECTION: postgres://postgres:password@database:5432/graphql?sslmode=disable
            CARTESI_DATABASE_CONNECTION: postgres://postgres:password@database:5432/rollupsdb?sslmode=disable
        expose:
            - 8080
        command: ["cartesi-rollups-graphql"]
        healthcheck:
            test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8080/health"]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5
        depends_on:
            database:
                condition: service_healthy

    proxy:
        volumes:
            - ./proxy/graphql.yaml:/etc/traefik/conf.d/graphql.yaml
