services:
    espresso_database_creator:
        image: postgres:16
        command: ["createdb", "sequencer"]
        depends_on:
            database:
                condition: service_healthy
        environment:
            PGHOST: database
            PGPORT: 5432
            PGUSER: postgres
            PGPASSWORD: password
            PGDATABASE: postgres

    espresso:
        image: ${CARTESI_SDK_IMAGE}
        command: ["espresso-dev-node"]
        deploy:
            resources:
                limits:
                    cpus: "4"
                    memory: "1G"
        ports:
            - 8770:8770
            - 8771:8771
            - 8772:8772
            - 20000:20000
        depends_on:
            espresso_database_creator:
                condition: service_completed_successfully
            anvil:
                condition: service_healthy
        environment:
            ESPRESSO_SEQUENCER_L1_PROVIDER: ${CARTESI_BLOCKCHAIN_HTTP_ENDPOINT:-http://anvil:8545}
            ESPRESSO_SEQUENCER_API_PORT: 8770
            ESPRESSO_BUILDER_PORT: 8771
            ESPRESSO_PROVER_PORT: 8772
            ESPRESSO_DEV_NODE_PORT: 20000
            ESPRESSO_SEQUENCER_POSTGRES_HOST: database
            ESPRESSO_SEQUENCER_POSTGRES_PORT: 5432
            ESPRESSO_SEQUENCER_POSTGRES_USER: postgres
            ESPRESSO_SEQUENCER_POSTGRES_PASSWORD: password
            ESPRESSO_SEQUENCER_POSTGRES_DATABASE: sequencer
            ESPRESSO_SEQUENCER_ETH_MNEMONIC: ${CARTESI_AUTH_MNEMONIC:-test test test test test test test test test test test junk}
            ESPRESSO_SEQUENCER_L1_POLLING_INTERVAL: "1s"
            ESPRESSO_STATE_PROVER_UPDATE_INTERVAL: "1s"
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-fsS",
                    "http://127.0.0.1:8770/status/block-height",
                ]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5

    rollups-node:
        environment:
            CARTESI_FEATURE_INPUT_READER_ENABLED: false

    espresso_reader_migration:
        image: ${CARTESI_SDK_IMAGE}
        command:
            - migrate
            - -source
            - file:///usr/share/cartesi/rollups-espresso-reader/migrations
            - -database
            - postgres://postgres:password@database:5432/postgres?sslmode=disable&x-migrations-table=espresso_schema_migrations
            - up
        depends_on:
            rollups-node-migration:
                condition: service_completed_successfully

    espresso_reader:
        image: ${CARTESI_SDK_IMAGE}
        command: ["cartesi-rollups-espresso-reader"]
        env_file:
            - ${CARTESI_BIN_PATH}/compose/rollups/default.env
        ports:
            - 8081
        depends_on:
            espresso_reader_migration:
                condition: service_completed_successfully
            espresso:
                condition: service_healthy
        environment:
            CARTESI_POSTGRES_ENDPOINT: postgres://postgres:password@database:5432/postgres?sslmode=disable
            ESPRESSO_SERVICE_ENDPOINT: ":8081"
            ESPRESSO_BASE_URL: http://espresso:8770
            ESPRESSO_NAMESPACE: 51025
            ESPRESSO_STARTING_BLOCK: 101

    proxy:
        depends_on:
            espresso:
                condition: service_healthy
        volumes:
            - ./proxy/espresso.yaml:/etc/traefik/conf.d/espresso.yaml
            - ./proxy/espresso-reader.yaml:/etc/traefik/conf.d/espresso-reader.yaml
