services:
    database_creator:
        image: postgres:16-alpine
        command: ["createdb", "squid"]
        depends_on:
            database:
                condition: service_healthy
        environment:
            PGHOST: ${PGHOST:-database}
            PGPORT: ${PGPORT:-5432}
            PGUSER: ${PGUSER:-postgres}
            PGPASSWORD: ${PGPASSWORD:-password}
            PGDATABASE: ${PGDATABASE:-postgres}

    explorer_api:
        image: cartesi/rollups-explorer-api:0.5.0
        environment:
            DB_NAME: ${PGDATABASE:-squid}
            DB_PORT: ${PGPORT:-5432}
            DB_HOST: ${PGHOST:-database}
            DB_PASS: ${PGPASSWORD:-password}
            GQL_PORT: 4350
        expose:
            - 4350
        command: ["sqd", "serve:prod"]
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-f",
                    "http://127.0.0.1:4350/graphql?query=%7B__typename%7D",
                ]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5
        depends_on:
            database_creator:
                condition: service_completed_successfully

    squid_processor:
        image: cartesi/rollups-explorer-api:0.5.0
        environment:
            CHAIN_ID: ${CHAIN_ID:-31337}
            RPC_URL_31337: ${RPC_URL:-http://anvil:8545}
            BLOCK_CONFIRMATIONS_31337: 0
            DB_NAME: ${PGDATABASE:-squid}
            DB_PORT: ${PGPORT:-5432}
            DB_HOST: ${PGHOST:-database}
            DB_PASS: ${PGPASSWORD:-password}
        command: ["sqd", "process:prod"]
        depends_on:
            database_creator:
                condition: service_completed_successfully

    explorer:
        image: cartesi/rollups-explorer:0.12.0
        expose:
            - 3000
        depends_on:
            database_creator:
                condition: service_completed_successfully

    proxy:
        depends_on:
            explorer_api:
                condition: service_healthy
            explorer:
                condition: service_healthy
        volumes:
            - ./proxy/explorer.yaml:/etc/traefik/conf.d/explorer.yaml
            - ./proxy/explorer-api.yaml:/etc/traefik/conf.d/explorer-api.yaml
