services:
    espresso:
        image: ${CARTESI_SDK_IMAGE}
        command: ["espresso-dev-node"]
        init: true
        deploy:
            resources:
                limits:
                    cpus: "4"
                    memory: "1G"
        depends_on:
            database:
                condition: service_healthy
            anvil:
                condition: service_healthy
        environment:
            ESPRESSO_SEQUENCER_L1_PROVIDER: ${CARTESI_BLOCKCHAIN_HTTP_ENDPOINT:-http://anvil:8545}
            ESPRESSO_SEQUENCER_API_PORT: 24000
            ESPRESSO_BUILDER_PORT: 23000
            ESPRESSO_DEV_NODE_PORT: 20000
            ESPRESSO_SEQUENCER_ETH_MNEMONIC: ${CARTESI_AUTH_MNEMONIC:-test test test test test test test test test test test junk}
            ESPRESSO_SEQUENCER_L1_POLLING_INTERVAL: "5s"
            ESPRESSO_STATE_PROVER_UPDATE_INTERVAL: "10s"
            ESPRESSO_SEQUENCER_DATABASE_MAX_CONNECTIONS: 25
            ESPRESSO_SEQUENCER_STORAGE_PATH: /data/espresso
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-fsS",
                    "http://127.0.0.1:24000/status/block-height",
                ]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5

    espresso_reader:
        image: ${CARTESI_SDK_IMAGE}
        command: ["cartesi-rollups-espresso-reader"]
        env_file:
            - ${CARTESI_BIN_PATH}/compose/rollups/default.env
        ports:
            - 8081
        depends_on:
            database:
                condition: service_healthy
            espresso:
                condition: service_healthy
        environment:
            CARTESI_DATABASE_CONNECTION: postgres://postgres:password@database:5432/rollupsdb?sslmode=disable
            ESPRESSO_SERVICE_ENDPOINT: ":8081"
            ESPRESSO_BASE_URL: http://espresso:24000

    proxy:
        volumes:
            - ./proxy/espresso.yaml:/etc/traefik/conf.d/espresso.yaml
