services:
    proxy:
        image: traefik:v3.3.4
        healthcheck:
            test: ["CMD", "traefik", "healthcheck", "--ping"]
            start_period: 5s
            start_interval: 200ms
            timeout: 500s
            retries: 20
        command:
            [
                "--ping=true",
                "--entryPoints.web.address=:8088",
                "--entryPoints.traefik.address=:8080",
                "--metrics.prometheus=true",
                "--metrics.prometheus.addServicesLabels=true",
                "--providers.file.directory=/etc/traefik/conf.d",
                "--providers.file.watch=true",
            ]
        ports:
            - ${CARTESI_LISTEN_PORT:-8080}:8088
