services:
    rollups-node:
        image: ${CARTESI_SDK_IMAGE}
        depends_on:
            database:
                condition: service_healthy
            anvil:
                condition: service_healthy
        expose:
            - "10000"
            - "10011"
            - "10012"
        healthcheck:
            test: ["CMD", "curl", "-fsS", "http://127.0.0.1:10000/livez"]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5
        entrypoint:
            - /bin/sh
            - -c
            - 'cartesi-rollups-cli db upgrade && exec "$0" "$@"'
        command: ["cartesi-rollups-node"]
        env_file:
            - ${CARTESI_BIN_PATH}/compose/rollups/default.env

    proxy:
        depends_on:
            rollups-node:
                condition: service_healthy
        volumes:
            - ./proxy/rollups-node.yaml:/etc/traefik/conf.d/rollups-node.yaml
