services:
    graphql_database_creator:
        image: postgres:16-alpine
        command: ["createdb", "graphql"]
        depends_on:
            database:
                condition: service_healthy
        environment:
            PGHOST: database
            PGPORT: 5432
            PGUSER: postgres
            PGPASSWORD: password
            PGDATABASE: postgres

    graphql_database_migration:
        image: ${CARTESI_SDK_IMAGE}
        command:
            - migrate
            - -path
            - /usr/share/cartesi/rollups-graphql/migrations
            - -database
            - postgres://postgres:password@database:5432/graphql?sslmode=disable
            - up
        depends_on:
            graphql_database_creator:
                condition: service_completed_successfully

    graphql:
        image: ${CARTESI_SDK_IMAGE}
        environment:
            POSTGRES_GRAPHQL_DB_URL: postgres://postgres:password@database:5432/graphql?sslmode=disable
            POSTGRES_NODE_DB_URL: postgres://postgres:password@database:5432/postgres?sslmode=disable
        expose:
            - 8080
        command: ["cartesi-rollups-graphql"]
        healthcheck:
            test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8080/health"]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5
        depends_on:
            graphql_database_migration:
                condition: service_completed_successfully

    proxy:
        depends_on:
            graphql:
                condition: service_healthy
        volumes:
            - ./proxy/graphql.yaml:/etc/traefik/conf.d/graphql.yaml
