services:
    graphql_database_creator:
        image: postgres:16-alpine
        command: ["createdb", "graphql"]
        depends_on:
            database:
                condition: service_healthy
        environment:
            PGHOST: database
            PGPORT: 5432
            PGUSER: postgres
            PGPASSWORD: password
            PGDATABASE: postgres

    graphql_database_migration:
        image: ${CARTESI_SDK_IMAGE}
        command:
            - migrate
            - -path
            - /usr/share/cartesi/rollups-graphql/migrations
            - -database
            - postgres://postgres:password@database:5432/graphql?sslmode=disable
            - up
        depends_on:
            graphql_database_creator:
                condition: service_completed_successfully

    graphql:
        image: ${CARTESI_SDK_IMAGE}
        environment:
            POSTGRES_GRAPHQL_DB_URL: postgres://postgres:password@database:5432/graphql?sslmode=disable
            POSTGRES_NODE_DB_URL: postgres://postgres:password@database:5432/postgres?sslmode=disable
        expose:
            - 8080
        command: ["cartesi-rollups-graphql"]
        depends_on:
            graphql_database_migration:
                condition: service_completed_successfully

    prompt:
        image: debian:bookworm-slim
        environment:
            PROMPT_TXT_03_GRAPHQL: "GraphQL endpoint running at http://localhost:${CARTESI_LISTEN_PORT}/graphql/"

    proxy:
        volumes:
            - ./proxy/graphql.yaml:/etc/traefik/conf.d/graphql.yaml
