services:
    espresso_database_creator:
        image: postgres:16
        command: ["createdb", "sequencer"]
        depends_on:
            database:
                condition: service_healthy
        environment:
            PGHOST: ${PGHOST:-database}
            PGPORT: ${PGPORT:-5432}
            PGUSER: ${PGUSER:-postgres}
            PGPASSWORD: ${PGPASSWORD:-password}
            PGDATABASE: ${PGDATABASE:-postgres}

    rollups-node:
        environment:
            CARTESI_FEATURE_INPUT_READER_ENABLED: false

    espresso:
        image: ${CARTESI_SDK_IMAGE}
        command: ["espresso-dev-node"]
        deploy:
            resources:
                limits:
                    cpus: "4"
                    memory: "1G"
        ports:
            - 8770:8770
            - 8771:8771
            - 8772:8772
            - 20000:20000
        depends_on:
            espresso_database_creator:
                condition: service_completed_successfully
            database:
                condition: service_healthy
        environment:
            ESPRESSO_SEQUENCER_L1_PROVIDER: ${CARTESI_BLOCKCHAIN_HTTP_ENDPOINT:-http://anvil:8545}
            ESPRESSO_SEQUENCER_API_PORT: 8770
            ESPRESSO_BUILDER_PORT: 8771
            ESPRESSO_PROVER_PORT: 8772
            ESPRESSO_DEV_NODE_PORT: 20000
            ESPRESSO_SEQUENCER_POSTGRES_HOST: database
            ESPRESSO_SEQUENCER_POSTGRES_PORT: 5432
            ESPRESSO_SEQUENCER_POSTGRES_USER: postgres
            ESPRESSO_SEQUENCER_POSTGRES_PASSWORD: password
            ESPRESSO_SEQUENCER_POSTGRES_DATABASE: sequencer
            ESPRESSO_SEQUENCER_ETH_MNEMONIC: ${CARTESI_AUTH_MNEMONIC:-test test test test test test test test test test test junk}
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-fsS",
                    "http://127.0.0.1:8770/status/block-height",
                ]
            start_period: 10s
            start_interval: 200ms
            interval: 10s
            timeout: 1s
            retries: 5

    proxy:
        depends_on:
            espresso:
                condition: service_healthy
        volumes:
            - ./proxy/espresso.yaml:/etc/traefik/conf.d/espresso.yaml
