services:
    mock-verifying-paymaster:
        image: cartesi/sdk:devel
        command: "mock-verifying-paymaster"
        environment:
            - ALTO_RPC=http://alto:4337
            - ANVIL_RPC=http://anvil:8545

    proxy:
        volumes:
            - ./proxy/paymaster.yaml:/etc/traefik/conf.d/paymaster.yaml
