name = 'cartesi-rollups-devnet'
version = '<%= package.version %>'
description = 'Cartesi Rollups Devnet'

[pull.cartesiRollups]
source = "cartesi-rollups:2.0.0@main"

[pull.entrypointSimulations]
source = "pimlico-entrypoint-simulations:0.7.0@main"

[pull.simpleAccount06]
source = "eth-infinitism-simple-account:0.6.0@main"

[pull.simpleAccount07]
source = "eth-infinitism-simple-account:0.7.0@main"

[pull.simpleAccount08]
source = "eth-infinitism-simple-account:0.8.0@main"

[pull.zerodevKernel030]
source = "zerodev-kernel:0.3.0@main"

[pull.zerodevKernel031]
source = "zerodev-kernel:0.3.1@main"

[pull.zerodevKernel032]
source = "zerodev-kernel:0.3.2@main"

[pull.zerodevKernelSudoPolicy]
source = "zerodev-kernel-sudo-policy:0.0.1@main"

[pull.zerodevKernelCallPolicy]
source = "zerodev-kernel-call-policy:0.0.1@main"

[pull.zerodevKernelCallPolicy2]
source = "zerodev-kernel-call-policy:0.0.2@main"

[pull.zerodevKernelCallPolicy3]
source = "zerodev-kernel-call-policy:0.0.3@main"

[pull.zerodevKernelCallPolicy4]
source = "zerodev-kernel-call-policy:0.0.4@main"

[pull.zerodevKernelGasPolicy]
source = "zerodev-kernel-gas-policy:0.0.1@main"

[pull.zerodevKernelTimestampPolicy]
source = "zerodev-kernel-timestamp-policy:0.0.1@main"

[pull.zerodevKernelRatelimitPolicy]
source = "zerodev-kernel-ratelimit-policy:0.0.1@main"

[pull.zerodevKernelSignaturePolicy]
source = "zerodev-kernel-signature-policy:0.0.1@main"

[pull.zerodevKernelEcdsaSigner]
source = "zerodev-kernel-ecdsa-signer:0.0.1@main"

[pull.zerodevKernelWebAuthnSigner]
source = "zerodev-kernel-web-authn-signer:0.0.1@main"

[pull.zerodevKernelWebAuthnSigner2]
source = "zerodev-kernel-web-authn-signer:0.0.2@main"

[pull.zerodevKernelAuthnValidator]
source = "zerodev-kernel-authn-validator:0.0.1@main"

[pull.zerodevKernelAuthnValidator2]
source = "zerodev-kernel-authn-validator:0.0.2@main"

[pull.alchemyLightAccountV1]
source = "alchemy-light-account:1.1.0@main"

[pull.alchemyLightAccountV2]
source = "alchemy-light-account:2.0.0@main"

[pull.alchemyModularAccountV2]
source = "alchemy-modular-account:2.0.0@main"

[var.Settings]
token_owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

[deploy.TestMultiToken]
artifact = "TestMultiToken"
args = ["<%= settings.token_owner %>"]

[deploy.TestNFT]
artifact = "TestNFT"
args = ["<%= settings.token_owner %>"]

[deploy.TestToken]
artifact = "TestToken"
args = ["<%= settings.token_owner %>"]
