name: cli
on:
    pull_request:
        paths:
            - ".github/workflows/cli.yaml"
            - "apps/cli/**"
            - "packages/tsconfig/**"
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: true
permissions:
    contents: read
    packages: write
    pull-requests: write
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Set up QEMU
              uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

            - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build
              run: bun run build --filter @cartesi/cli

            - name: Type check
              run: bun run --cwd apps/cli typecheck:tsc

            - name: Test
              run: bun test apps/cli/

            - name: Coverage Report
              uses: 70-10/bun-coverage-report-action@6173866ce2a31456a726ff3f4c91f230bd94a9e9 # v1.0.3
              if: always()
              with:
                  lcov-path: coverage/lcov.info
