name: cli
on:
    pull_request:
        paths:
            - .github/workflows/cli.yaml
            - apps/cli/**
            - packages/contracts/**
            - packages/tsconfig/**
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: true
permissions:
    contents: read
    packages: write
    pull-requests: write
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}
        steps:
            - name: Checkout
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
            - name: Setup Node.js 20
              uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"
                  cache: "pnpm"

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # 1.3.1
              with:
                  version: v0.3.0

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build --filter @cartesi/cli

            - name: Test
              run: pnpm test --filter @cartesi/cli

            - name: "Report Coverage"
              if: always()
              uses: davelosert/vitest-coverage-report-action@5a78cb16e761204097ad8a39369ea5d0ff7c8a5d # v2.8.0
              with:
                  working-directory: ./apps/cli
