name: cli
on:
    workflow_call:
        inputs:
            release:
                type: boolean
                required: false
        secrets:
            NPM_TOKEN:
                required: true
            TURBO_TOKEN:
                required: true
    pull_request:
        paths:
            - .github/workflows/cli.yaml
            - apps/cli/**
            - packages/contracts/**
            - packages/eslint-config/**
            - packages/tsconfig/**
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: true
permissions:
    contents: read
    packages: write
    pull-requests: write
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
            - name: Setup Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"
                  cache: "pnpm"

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1

            - name: Install dependencies
              run: pnpm install

            - name: Test / Coverage
              working-directory: ./apps/cli
              run: pnpm run test:coverage

            - name: "Report Coverage"
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
              with:
                  working-directory: ./apps/cli

            - name: Build
              run: pnpm build --filter @cartesi/cli

            - name: Publish
              if: ${{ inputs.release }}
              working-directory: ./apps/cli
              run: pnpm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
