name: cli
on:
    pull_request:
        paths:
            - ".github/workflows/cli.yaml"
            - "apps/cli/**"
            - "packages/tsconfig/**"
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: true
permissions:
    contents: read
    packages: write
    pull-requests: write
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}
        steps:
            - name: Checkout
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2.1.0

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@8b0419c685ef46cb79ec93fbdc131174afceb730 # 1.6.0
              with:
                  version: v1.4.3

            - name: Install dependencies
              run: bun install

            - name: Build
              run: bun run build --filter @cartesi/cli

            - name: Test
              run: bun test --coverage --coverage-reporter=lcov --coverage-dir=coverage apps/cli/

            - name: Coverage Report
              uses: 70-10/bun-coverage-report-action@6173866ce2a31456a726ff3f4c91f230bd94a9e9 # v1.0.3
              if: always()
              with:
                lcov-path: coverage/lcov.info
