name: paymaster
on:
    pull_request:
        paths:
            - ".github/workflows/paymaster.yaml"
            - "packages/mock-verifying-paymaster/**"
            - "packages/tsconfig/**"
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: true
permissions:
    contents: read
    packages: write
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1.9.1
              with:
                  version: v1.4.3

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build
              run: bun run build --filter @cartesi/mock-verifying-paymaster
