name: Release
on:
    push:
        branches:
            - main
            - release/*
            - prerelease/*
permissions:
    actions: write
    contents: write
    id-token: write
    packages: write
    pull-requests: write
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        outputs:
            published: ${{ steps.changeset.outputs.published }}
            publishedPackages: ${{ steps.changeset.outputs.publishedPackages }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  fetch-depth: 0

            - uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2.1.0

            # Minimum required version for npm publish with OIDC Support
            # https://docs.npmjs.com/trusted-publishers
            - run: |
                  npm install -g npm@latest
                  npm --version

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@8b0419c685ef46cb79ec93fbdc131174afceb730 # 1.6.0
              with:
                  version: v1.4.3

            - name: Install Dependencies
              run: bun install

            - name: Build
              run: bun run build

            - name: Test
              run: bun run test

            - name: "Report Coverage"
              if: always()
              uses: davelosert/vitest-coverage-report-action@5a78cb16e761204097ad8a39369ea5d0ff7c8a5d # v2.8.0
              with:
                  working-directory: ./apps/cli

            - name: Create Release Pull Request or Publish to npm
              id: changeset
              uses: changesets/action@06245a4e0a36c064a573d4150030f5ec548e4fcc # v1.4.10
              with:
                  commit: "release: version packages"
                  publish: bun run publish-packages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    packages_to_build:
        name: Get released packages
        runs-on: ubuntu-latest
        needs: release
        if: ${{ needs.release.outputs.published == 'true' }}
        outputs:
            packages: ${{ steps.packages.outputs.PACKAGES }}
        steps:
            - name: Get released packages
              id: packages
              run: |
                  echo "PACKAGES=$(jq -c '[ .[].name ]' <(echo '${{ needs.release.outputs.publishedPackages }}'))" >> "$GITHUB_OUTPUT"

    build_sdk:
        name: Build sdk
        needs: [release, packages_to_build]
        if: ${{ needs.release.outputs.published == 'true' && contains(fromJSON(needs.packages_to_build.outputs.packages), '@cartesi/sdk') }}
        uses: ./.github/workflows/sdk.yaml
        secrets: inherit
